/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedPontoRouteImport } from './routes/_authenticated/ponto'
import { Route as AuthenticatedRodizioRouteImport } from './routes/_authenticated/rodizio'
import { Route as AuthenticatedSetoresRouteImport } from './routes/_authenticated/setores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPontoRoute = AuthenticatedPontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRodizioRoute = AuthenticatedRodizioRouteImport.update({
  id: '/rodizio',
  path: '/rodizio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetoresRoute = AuthenticatedSetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/ponto': typeof AuthenticatedPontoRoute
  '/rodizio': typeof AuthenticatedRodizioRoute
  '/setores': typeof AuthenticatedSetoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/ponto': typeof AuthenticatedPontoRoute
  '/rodizio': typeof AuthenticatedRodizioRoute
  '/setores': typeof AuthenticatedSetoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/ponto': typeof AuthenticatedPontoRoute
  '/_authenticated/rodizio': typeof AuthenticatedRodizioRoute
  '/_authenticated/setores': typeof AuthenticatedSetoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/equipe' | '/ponto' | '/rodizio' | '/setores'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/equipe' | '/ponto' | '/rodizio' | '/setores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/equipe'
    | '/_authenticated/ponto'
    | '/_authenticated/rodizio'
    | '/_authenticated/setores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ponto': {
      id: '/_authenticated/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof AuthenticatedPontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rodizio': {
      id: '/_authenticated/rodizio'
      path: '/rodizio'
      fullPath: '/rodizio'
      preLoaderRoute: typeof AuthenticatedRodizioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setores': {
      id: '/_authenticated/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof AuthenticatedSetoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedPontoRoute: typeof AuthenticatedPontoRoute
  AuthenticatedRodizioRoute: typeof AuthenticatedRodizioRoute
  AuthenticatedSetoresRoute: typeof AuthenticatedSetoresRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedPontoRoute: AuthenticatedPontoRoute,
  AuthenticatedRodizioRoute: AuthenticatedRodizioRoute,
  AuthenticatedSetoresRoute: AuthenticatedSetoresRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
